input_data_path: "data/raw/heart.csv"
output_model_path: "results/models/lr_model.pkl"
metrics_path: "results/scores/lr_metrics.json"
preds_path: "results/preds/lr_preds.csv"
split_params:
  val_size: 0.2
  random_state: 42
preprocess_params:
  drop_nan: True
  drop_duplicates: False
features_params:
  categorical_features:
    - "sex"
    - "cp"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
    - "fbs"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  target_col: "target"